POST http://localhost:5000/company/new
Content-Type: application/json

{
    "name":"Test",
    "email":"testing@test.com",
    "DtsNo":"ID-234",
    "url":"https://www.youtube.com/",
    "instaUsername":"msarimhassan",
    "whatsappNo":"03244628572",
    "isOrg":"Yes"
}
###

GET http://localhost:5000/users/findbyemail/daimhassan12@gmail.com

###
POST http://localhost:5000/users/new
Content-Type: application/json

{
    "Name":"Sarim",
    "Email":"sarimhassan5@gmail.com",
    "Gender":"Male"
}

###

POST http://localhost:5000/company/addtour/testing@test.com
Content-Type: application/json

{
    "name":"sarim",
    "class":"nine"
}

###
GET http://localhost:5000/company/tourcount/msarimdev@gmail.com

###
GET http://localhost:5000/company/getcompanydata/msarimdev@gmail.com

###
DELETE   http://localhost:5000/company/deletetour/9z3P1zGIANFhhve64neg

###
POST  http://localhost:5000/company/addtour
Content-Type: application/json


###
GET http://localhost:5000/company/gettours/xyz@gmail.com

###
GET http://localhost:5000/company/gettour/FWNPNMQrtfVpBZUBt7bq

###
PUT http://localhost:5000/company/updatecompanyinsta/msarimdev@gmail.com
Content-Type: application/json

{
    "insta":"iphone"
}

###
PUT http://localhost:5000/company/updatecompanywhatsapp/msarimdev@gmail.com
Content-Type: application/json

{
    "whatsapp":"03244628572"
}

###
PUT http://localhost:5000/company/updatecompanywebsite/msarimdev@gmail.com
Content-Type: application/json

{
    "url":"hello website"
}

###
Get http://localhost:5000/users/getalltours

###
POST http://localhost:5000/users/addfavourite
Content-Type: application/json

{
"companyName": "Adventure Tours Pakistan",
"date": "2022-05-26",
"details": " 1 day Visit to altit and baltit fort \nNanga partbat view point \nJunction\nchina border\n",
"duration": "3",
"imgUrl": "https://firebasestorage.googleapis.com/v0/b/trekxplorer.appspot.com/o/images%2FWallpaperDog-951903.jpg?alt=media&token=f0653c1d-dd99-4a12-847d-b2177092a668",
"instaUsername": "msarimhassan",
"location": "Hunza",
"price": "12000",
"title": "Tour to Hunza",
"url": "youtube.com",
"whatsappNo": "03219453316",
"email":"msarimdev@gmail.com",
"id":"Sn5YQfiazqrS0jABHUmn"
}
###
GET http://localhost:5000/users/getfavourite/msarimdev@gmail.com

###
DELETE http://localhost:5000/users/deletefavourite/nVmi9xpjL54Wfa1Eso68

###
PUT http://localhost:5000/users/updatename/sarimhassan5@gmail.com
Content-Type: application/json

{
    "name":"harry"
}

###
GET http://localhost:5000/company/countlikes/Baltistan Tours


###
Get http://localhost:5000/company/getfeedback/Baltistan Tours


###
Get http://localhost:5000/users/get-count

###
Get http://localhost:5000/users/get-company-count
###
Get http://localhost:5000/users/get-user-count